project:
  type: book
  output-dir: docs

book:
  title: "DS 2023 Final Project"
  author: "Kylie Stephens, Avalon Bennett, Will Wert" 
  favicon: logo.png
  description: "Analyzing and Revamping ACLR Data"
  keyword: "data science, communicating, data visualization"
  url: "https://github.com/kyliestephens/DS2023_Final"

  sidebar:
    logo: logo.png 
    search: true

  repo-url: "https://github.com/kyliestephens/DS2023_Final"
  image: logo.png

  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd 
    - dataviz.qmd
    - datadictionary.qmd

format: 
  html:
    theme:
      light: minty 
    code-fold: false 
    backgroundcolor: "#FFFFFF"
